 version: "3.9"

 services:
  db:
      image: postgres
      container_name: db_postgres
      env_file: ./MyPlannerProject/.env
      ports:
        - "5432:5432"

  web:
    build: .
    container_name: backend_django
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    env_file: ./MyPlannerProject/.env
    depends_on:
      - db
