 version: "3.9"

 services:
  db:
      image: postgres
      container_name: db_postgres
      environment: 
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=k44wy3p51
      ports:
        - "5432:5432"

  web:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=k44wy3p51
    depends_on:
      - db
