# Generated by Django 4.0.3 on 2022-04-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='list',
            new_name='task_list',
        ),
    ]
