# Generated by Django 4.0.3 on 2022-05-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_alter_list_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
